#!C:\AI Downloads\AI Coding Project\Cursor Projects\livekit-py-agent-master\WhisperLiveKit\test_cuda_126\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
